// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: furya/airdrop/v1beta1/allocation.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AirdropAllocation defines the user's airdrop allocation.
type AirdropAllocation struct {
	Chain         string                                  `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Address       string                                  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount        github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount"`
	ClaimedAmount github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,4,opt,name=claimed_amount,json=claimedAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"claimed_amount"`
}

func (m *AirdropAllocation) Reset()         { *m = AirdropAllocation{} }
func (m *AirdropAllocation) String() string { return proto.CompactTextString(m) }
func (*AirdropAllocation) ProtoMessage()    {}
func (*AirdropAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2094555ab5bcc900, []int{0}
}
func (m *AirdropAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AirdropAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AirdropAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AirdropAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AirdropAllocation.Merge(m, src)
}
func (m *AirdropAllocation) XXX_Size() int {
	return m.Size()
}
func (m *AirdropAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AirdropAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_AirdropAllocation proto.InternalMessageInfo

func (m *AirdropAllocation) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *AirdropAllocation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*AirdropAllocation)(nil), "furya.airdrop.v1beta1.AirdropAllocation")
}

func init() {
	proto.RegisterFile("furya/airdrop/v1beta1/allocation.proto", fileDescriptor_2094555ab5bcc900)
}

var fileDescriptor_2094555ab5bcc900 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x63, 0x7e, 0x8a, 0xb0, 0x04, 0x12, 0x51, 0x91, 0x42, 0x07, 0x17, 0x31, 0x00, 0x4b,
	0x63, 0x15, 0x9e, 0xa0, 0x65, 0x60, 0x61, 0xea, 0xc0, 0xc0, 0x52, 0xdd, 0xc6, 0x21, 0xb5, 0x68,
	0x72, 0x23, 0xdb, 0x41, 0xf4, 0x2d, 0x78, 0xac, 0x8e, 0x1d, 0x11, 0x43, 0x85, 0x12, 0x1e, 0x04,
	0xc5, 0x36, 0x15, 0x33, 0x93, 0xef, 0xf1, 0x39, 0xfe, 0x8e, 0x74, 0x4d, 0x2f, 0x9f, 0x2b, 0xb5,
	0x04, 0x0e, 0x52, 0x09, 0x85, 0x25, 0x7f, 0x1d, 0xce, 0x52, 0x03, 0x43, 0x0e, 0x8b, 0x05, 0x26,
	0x60, 0x24, 0x16, 0x71, 0xa9, 0xd0, 0x60, 0x78, 0x6a, 0x73, 0xb1, 0xcf, 0xc5, 0x3e, 0xd7, 0xeb,
	0x66, 0x98, 0xa1, 0x4d, 0xf0, 0x76, 0x72, 0xe1, 0xde, 0x59, 0x82, 0x3a, 0x47, 0x3d, 0x75, 0x86,
	0x13, 0xce, 0xba, 0xf8, 0x26, 0xf4, 0x64, 0xe4, 0x20, 0xa3, 0x6d, 0x47, 0xd8, 0xa5, 0xfb, 0xc9,
	0x1c, 0x64, 0x11, 0x91, 0x73, 0x72, 0x7d, 0x38, 0x71, 0x22, 0x8c, 0xe8, 0x01, 0x08, 0xa1, 0x52,
	0xad, 0xa3, 0x1d, 0x7b, 0xff, 0x2b, 0xc3, 0x7b, 0xda, 0x81, 0x1c, 0xab, 0xc2, 0x44, 0xbb, 0xad,
	0x31, 0xe6, 0xab, 0x4d, 0x3f, 0xf8, 0xdc, 0xf4, 0xaf, 0x32, 0x69, 0xe6, 0xd5, 0x2c, 0x4e, 0x30,
	0xf7, 0xb5, 0xfe, 0x18, 0x68, 0xf1, 0xc2, 0xcd, 0xb2, 0x4c, 0x75, 0x7c, 0x87, 0xb2, 0x98, 0xf8,
	0xe7, 0xe1, 0x23, 0x3d, 0x4e, 0x16, 0x20, 0xf3, 0x54, 0x4c, 0x3d, 0x70, 0xef, 0x7f, 0xc0, 0x23,
	0x8f, 0x19, 0x59, 0xca, 0xf8, 0x61, 0x55, 0x33, 0xb2, 0xae, 0x19, 0xf9, 0xaa, 0x19, 0x79, 0x6f,
	0x58, 0xb0, 0x6e, 0x58, 0xf0, 0xd1, 0xb0, 0xe0, 0xe9, 0xe6, 0x0f, 0xb1, 0xdd, 0xa9, 0x2e, 0x51,
	0x19, 0x3b, 0xc1, 0xa0, 0x2a, 0x33, 0x05, 0x22, 0xe5, 0x6f, 0xdb, 0xff, 0xb0, 0x0d, 0xb3, 0x8e,
	0xdd, 0xdd, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x76, 0x97, 0x60, 0xad, 0x01, 0x00,
	0x00,
}

func (m *AirdropAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AirdropAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AirdropAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ClaimedAmount.Size()
		i -= size
		if _, err := m.ClaimedAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAllocation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAllocation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAllocation(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintAllocation(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAllocation(dAtA []byte, offset int, v uint64) int {
	offset -= sovAllocation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AirdropAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovAllocation(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAllocation(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovAllocation(uint64(l))
	l = m.ClaimedAmount.Size()
	n += 1 + l + sovAllocation(uint64(l))
	return n
}

func sovAllocation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAllocation(x uint64) (n int) {
	return sovAllocation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AirdropAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAllocation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AirdropAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AirdropAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAllocation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAllocation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAllocation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAllocation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAllocation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAllocation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAllocation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAllocation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAllocation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAllocation = fmt.Errorf("proto: unexpected end of group")
)
