name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # furyad hangs on ubuntu runner
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout furya-dapp repo
        uses: actions/checkout@v4
        with:
          repository: FURYA/furya-dapp
          path: furya-dapp
          ref: 7e968801a0a03f47f59dd7683f1653935222ea88

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "furya-dapp/yarn.lock"

      - name: Run integration tests
        run: make integration-tests
        env:
          FURYA_DAPP_REPO: furya-dapp
